"""Build everything a `katsuji.toml` describes: font files, string blobs, constants."""

from __future__ import annotations

from pathlib import Path

from script import Table

from katsuji.atlas import Atlas
from katsuji.config import Config, ConfigError, FontConfig, StringsConfig
from katsuji.formats import VwfFont
from katsuji.kerning import find_kerning
from katsuji.strings import index_entry, pack_runs, text_tiles


def build(config: Config) -> list[Path]:
    """Write every output of `config`; returns the paths written."""
    written: list[Path] = []
    fonts = {name: _build_font(font, written) for name, font in config.fonts.items()}
    for strings in config.strings.values():
        _build_strings(strings, fonts[strings.font], config.fonts[strings.font], written)
    return written


def _table(path: Path | None, where: str) -> Table:
    if path is None:
        raise ConfigError(f"[{where}] needs a `table` to encode its text")
    return Table(str(path))


def _pair(table: Table, text: str, where: str) -> tuple[int, int]:
    codes = table.to_bytes(text)
    if len(codes) != 2:
        raise ConfigError(f"[{where}] kerning pair {text!r} encodes to {len(codes)} codes, not 2")
    return codes[0], codes[1]


def _build_font(config: FontConfig, written: list[Path]) -> VwfFont:
    where = f"fonts.{config.name}"
    atlas = Atlas.open(config.png, config.cell_width, config.cell_height, config.grid)
    kerning: dict[tuple[int, int], int] = {}
    if config.kerning_candidates or config.kerning:
        table = _table(config.table, where)
        candidates = (table.to_bytes(text) for text in config.kerning_candidates)
        pairs = [(codes[0], codes[1]) for codes in candidates if len(codes) == 2]
        kerning = find_kerning(atlas, pairs, config.default_kerning)
        for text, pixels in config.kerning.items():
            kerning[_pair(table, text, where)] = pixels
    font = VwfFont.from_atlas(atlas, config.widths, kerning)
    _write(config.output, font.encode(), written)
    if config.constants:
        prefix = config.name.upper()
        _write_constants(
            config.constants,
            {
                f"{prefix}_FONT_HEIGHT": font.height,
                f"{prefix}_FONT_GLYPH_SIZE": font.height + 1,
                f"{prefix}_FONT_KERNING_PAIRS": len(font.kerning),
            },
            written,
        )
    return font


def _build_strings(config: StringsConfig, font: VwfFont, font_config: FontConfig, written: list[Path]) -> None:
    where = f"strings.{config.name}"
    table = _table(config.table or font_config.table, where)
    runs: list[bytes] = []
    counts: list[int] = []
    for text in config.texts:
        tiles, columns = text_tiles(
            font, table.to_bytes(text), config.bpp, config.ink, config.paper, config.gap, config.max_tiles
        )
        runs.append(tiles)
        counts.append(columns)
    blob, offsets = pack_runs(runs, config.bank_size)
    _write(config.blob, blob, written)
    _write(config.index, b"".join(index_entry(o, n) for o, n in zip(offsets, counts, strict=True)), written)
    if config.constants:
        prefix = config.name.upper()
        _write_constants(
            config.constants,
            {f"{prefix}_COUNT": len(config.texts), f"{prefix}_MAX_TILES": max(counts, default=0)},
            written,
        )


def _write(path: Path, data: bytes, written: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    written.append(path)


def _write_constants(path: Path, constants: dict[str, int], written: list[Path]) -> None:
    lines = ['"""Generated by katsuji build; do not edit."""', ""]
    lines += [f"{name} = {value:#x}" if value > 9 else f"{name} = {value}" for name, value in constants.items()]
    _write(path, ("\n".join(lines) + "\n").encode(), written)
